name: Deploy

on:
  workflow_run:
    workflows: [Test]
    types:
      - completed
    branches:
      - production
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.event.workflow_run.head_sha }}"
          echo  "${{ github.event.workflow_run.head_branch }}""
